name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  variables:
    runs-on: [ Linux, standard ]
    outputs:
      node-version: ${{ steps.outputs.outputs.node-version }}
      container-registry: ${{ steps.outputs.outputs.container-registry }}
      container-version: ${{ steps.outputs.outputs.container-version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - id: outputs
        name: Preparation job outputs
        run: |
          echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          echo "container-registry=$JFROG_DOCKER_BASE_URL-release.jfrog.io" >> "$GITHUB_OUTPUT"
          echo "container-version=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

  publish:
    needs: variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Restore npm dependencies
        uses: actions/cache/restore@v3
        env:
          cache-name: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}